"""Deterministic role-lane classification and resume tailoring guidance."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ResumeStrategy:
    lane: str
    headline: str
    summary: str
    core_skills: tuple[str, ...]
    methods_title: str | None
    methods: tuple[str, ...]
    tools: tuple[str, ...]
    projects: tuple[str, ...]
    excluded_projects: tuple[str, ...]
    experience_emphasis: tuple[str, ...]
    max_projects: int = 4
    max_project_bullets: int = 3
    project_section_title: str = "Projects"
    score: int = 0
    runner_up_score: int = 0
    low_confidence: bool = False


COMMON_TOOLS = ("OpenAI API", "GPT-5.5", "Python", "GitHub / GitHub Actions", "Figma", "GA4", "Google Tag Manager", "Pendo", "OneTrust", "Asana")


def _strategy(
    lane: str,
    headline: str,
    summary: str,
    skills: tuple[str, ...],
    methods_title: str | None,
    methods: tuple[str, ...],
    projects: tuple[str, ...],
    emphasis: tuple[str, ...],
    tools: tuple[str, ...] = COMMON_TOOLS,
    excluded: tuple[str, ...] = ("Job Fit Agent",),
    max_projects: int = 4,
    max_project_bullets: int = 3,
    project_section_title: str = "Projects",
) -> ResumeStrategy:
    return ResumeStrategy(
        lane,
        headline,
        summary,
        skills,
        methods_title,
        methods,
        tools,
        projects,
        excluded,
        emphasis,
        max_projects,
        max_project_bullets,
        project_section_title,
    )


STRATEGIES = {
    "ai_strategy_transformation": _strategy(
        "ai_strategy_transformation", "AI Transformation Leader | Enterprise AI Adoption | Workflow Automation",
        "Enterprise AI transformation leader focused on AI adoption, workflow automation, AI literacy, change enablement, stakeholder communications, scalable AI programs, and measurable productivity and operational outcomes.",
        ("Enterprise AI Strategy", "AI Transformation", "AI Adoption", "AI Literacy", "Workflow Automation", "Agentic AI Workflows", "Change Enablement", "Stakeholder Communications", "Communities of Practice", "AI Champion Programs", "Use Case Prioritization", "Program Leadership", "Responsible AI", "Prompt Strategy", "Training & Enablement", "Productivity Improvement", "Operational Performance"),
        "AI Transformation Methods", ("Enterprise AI Literacy", "AI Academy Program Design", "Champion Network Development", "Communities of Practice", "Workflow Mapping", "Use Case Intake", "AI Tool Enablement", "Prompt Design", "Responsible AI Practices", "Adoption Tracking", "Stakeholder Updates", "Executive Reporting", "Change Management", "Training Resources", "Automation Roadmaps", "Impact Measurement"),
        ("AI Marketing Intelligence Platform", "AI Product Design Operating System", "RWLV Priority Governor Agent", "Site Audit QA Agent"),
        ("enterprise adoption and enablement", "stakeholder and senior-leader communications", "change management", "measurable transformation outcomes"),
        ("OpenAI API", "GPT-5.5", "OpenClaw", "Hermes Agent", "Python", "GitHub / GitHub Actions", "Asana", "GA4", "Pendo", "Figma"),
        project_section_title="Selected AI Transformation & Workflow Automation Projects"),
    "ai_solutions_architecture": _strategy(
        "ai_solutions_architecture",
        "AI Solutions Architect | Knowledge Assistants | Agentic Workflow Systems",
        "AI solutions builder focused on knowledge assistants, agentic workflows, AI experimentation, technical documentation, evaluation planning, stakeholder alignment, and implementation-ready architecture across business, product, analytics, engineering, and vendor teams.",
        (
         "AI Solutions Architecture",
         "Knowledge Assistants",
            "AI Agents",
            "Agentic Workflows",
            "AI Experimentation",
            "Solution Design",
            "Technical Specifications",
            "Evaluation Planning",
            "AI Evals",
            "Benchmark Design",
            "Context Engineering",
            "Prompt Design",
            "Workflow Architecture",
            "Stakeholder Collaboration",
            "Vendor Evaluation",
            "Architecture Documentation",
            "Implementation Planning",
            "Responsible AI",
            "AI Governance",
            "Cross-Functional Enablement",
        ),
        "AI Solutions Architecture Methods",
        (
            "AI Use-Case Discovery",
            "Solution Architecture",
            "Knowledge Assistant Design",
            "Agent Workflow Design",
            "AI Experiment Planning",
            "Vendor / Platform Review",
            "Technical Specification Writing",
            "Context Engineering",
            "Prompt Design",
            "Evaluation Planning",
            "Benchmark Definition",
            "QA Review",
            "Implementation Readiness",
            "Stakeholder Alignment",
            "Architecture Documentation",
            "Cross-Functional Review",
            "Risk Documentation",
            "Continuous Learning",
        ),
        (
            "AI Product Design Operating System",
            "AI Marketing Intelligence Platform",
            "Job Fit Agent",
            "Site Audit QA Agent",
        ),
        (
            "AI solution architecture and knowledge assistant design",
            "agentic workflow experimentation and implementation planning",
            "evaluation planning, QA review, and benchmark definition",
            "stakeholder collaboration, documentation, and cross-functional enablement",
        ),
        (
            "ChatGPT",
            "Codex",
            "OpenAI API",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "pytest",
            "Asana",
            "Figma",
            "GA4",
            "Pendo",
            "Google Tag Manager",
            "OneTrust",
        ),
        max_projects=3,
        max_project_bullets=3,
        project_section_title="Selected AI Solutions, Agents & Evaluation Projects",
        
    ),
    "agentic_operations_architecture": _strategy(
        "agentic_operations_architecture",
        "Agentic Operations Architect | AI Workflow Standards | Service Transformation",
        "AI operations and product systems builder focused on reusable agentic workflow patterns, service transformation, human-in-the-loop review, QA safeguards, workflow metrics, governance, documentation, and cross-functional adoption across business, product, analytics, legal, security, and vendor teams.",
        (
            "Agentic Operations",
            "AI Workflow Architecture",
            "Service Transformation",
            "Reusable Workflow Patterns",
            "Agentic Workflow Standards",
            "Human-in-the-Loop Review",
            "Escalation Logic",
            "Override Controls",
            "Quality Safeguards",
            "Workflow Metrics",
            "Evaluation Planning",
            "Release Gating",
            "Post-Launch Monitoring",
            "Operational Governance",
            "Responsible AI",
            "Risk Management",
            "Process Mining",
            "SOP Review",
            "Customer Impact Prioritization",
            "Stakeholder Alignment",
            "Product Feedback Loops",
            "AI-Assisted Operations",
        ),
        "Agentic Operations Architecture Methods",
        (
            "Workflow Pattern Design",
            "Current-State Workflow Mapping",
            "SOP Review",
            "Automation Opportunity Ranking",
            "Risk Assessment",
            "Customer Impact Review",
            "Agentic Workflow Prototyping",
            "Human-in-the-Loop Design",
            "Escalation Path Design",
            "Override Logic",
            "QA Safeguards",
            "Evaluation Planning",
            "Release Criteria",
            "Post-Launch Monitoring",
            "Workflow Metrics",
            "Regression Review",
            "Governance Documentation",
            "Stakeholder Reviews",
            "Product Feedback Capture",
            "Reusable Standards",
        ),
        (
            "AI Product Design Operating System",
            "Site Audit QA Agent",
            "AI Marketing Intelligence Platform",
            "RWLV Priority Governor Agent",
        ),
        (
            "reusable agentic workflow patterns and standards",
            "HITL review, escalation logic, QA safeguards, and release criteria",
            "workflow metrics, post-launch monitoring, and regression review",
            "cross-functional governance, stakeholder reviews, and product feedback loops",
        ),
        (
            "ChatGPT",
            "Codex",
            "OpenAI API",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "pytest",
            "Asana",
            "Figma",
            "GA4",
            "Pendo",
            "Google Tag Manager",
            "OneTrust",
        ),
        project_section_title="Selected Agentic Operations, QA & AI Workflow Projects",
    ),
    "ai_data_operations_project_lead": _strategy(
        "ai_data_operations_project_lead",
        "Strategic Project Lead | AI Data Operations | QC Systems & Customer Delivery",
        "High-agency project and operations lead focused on end-to-end delivery, customer requirements, QA/QC systems, workflow operations, vendor and contributor coordination, documentation, and AI-assisted process improvement in fast-moving technical environments.",
        (
            "AI Data Operations",
            "Strategic Project Delivery",
            "End-to-End Ownership",
            "Customer Requirements",
            "Quality Control",
            "QC Systems",
            "Workflow Operations",
            "Contributor Coordination",
            "Vendor Coordination",
            "Project Intake",
            "Delivery Management",
            "Stakeholder Management",
            "Customer Communication",
            "Requirements Translation",
            "QA/UAT",
            "Operational Documentation",
            "Process Design",
            "Process Improvement",
            "Fast-Paced Execution",
            "Ambiguity Management",
            "AI-Assisted Operations",
            "Reporting",
        ),
        "AI Data Operations & Delivery Methods",
        (
            "Project Intake",
            "Customer Requirement Review",
            "Scope Definition",
            "Workflow Mapping",
            "Delivery Planning",
            "Contributor Coordination",
            "Vendor Coordination",
            "Quality Control",
            "QC Checklist Design",
            "QA/UAT",
            "Issue Triage",
            "Customer Updates",
            "Status Reporting",
            "Documentation",
            "Process Standardization",
            "Post-Delivery Review",
            "Operational Improvement",
            "AI-Assisted Documentation",
        ),
        (
            "Site Audit QA Agent",
            "AI Marketing Intelligence Platform",
            "RWLV Priority Governor Agent",
            "AI Product Design Operating System",
        ),
        (
            "end-to-end project delivery in ambiguous environments",
            "QA/QC systems, documentation, and operational repeatability",
            "customer requirements, stakeholder coordination, and vendor/contributor management",
            "AI-assisted operations and scalable workflow improvement",
        ),
        (
            "Asana",
            "Figma",
            "GA4",
            "Pendo",
            "Google Tag Manager",
            "OneTrust",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "pytest",
            "ChatGPT",
            "Codex",
            "OpenAI API",
        ),
        project_section_title="Selected AI Data Operations, QC & Delivery Projects",
    ),
    "technical_consulting_solutions_implementation": _strategy(
        "technical_consulting_solutions_implementation",
        "Technical Consultant | SaaS Implementations | Integrations & Workflow Architecture",
        "Technical consultant and implementation-focused product operator with experience translating business workflows into technical requirements, supporting integrations, coordinating vendors and stakeholders, documenting scalable processes, and driving customer-facing solutions from discovery through activation.",
        (
            "Technical Consulting",
            "Solutions Consulting",
            "Implementation Support",
            "Customer Discovery",
            "Workflow Mapping",
            "Integration Planning",
            "API Concepts",
            "System Architecture",
            "Configuration Guidance",
            "Requirements Gathering",
            "Stakeholder Management",
            "Technical Documentation",
            "Troubleshooting",
            "Customer Activation",
            "Time-to-Value",
            "Product Feedback Loops",
            "Cross-Functional Delivery",
            "Vendor Coordination",
            "Process Improvement",
            "Analytics & Reporting",
            "AI-Assisted Operations",
        ),
        "Technical Consulting & Implementation Methods",
        (
            "Technical Discovery",
            "Current-State Workflow Mapping",
            "Requirements Gathering",
            "Solution Design",
            "Integration Planning",
            "Configuration Review",
            "Stakeholder Translation",
            "Implementation Support",
            "Troubleshooting",
            "Escalation Management",
            "Vendor Coordination",
            "Documentation",
            "QA/UAT",
            "Customer Readiness",
            "Activation Support",
            "Post-Launch Reporting",
            "Product Feedback Capture",
            "Process Standardization",
            "AI-Assisted Documentation",
        ),
        (
            "Site Audit QA Agent",
            "AI Marketing Intelligence Platform",
            "AI Product Design Operating System",
            "RWLV Priority Governor Agent",
        ),
        (
            "technical consulting and customer-facing solution design",
            "workflow mapping, requirements, and integration planning",
            "implementation support, QA/UAT, and troubleshooting",
            "documentation, product feedback, and scalable operating patterns",
        ),
        (
            "Asana",
            "Figma",
            "GA4",
            "Pendo",
            "Google Tag Manager",
            "OneTrust",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "pytest",
            "ChatGPT",
            "Codex",
            "OpenAI API",
        ),
        project_section_title="Selected Technical Consulting, Integration & AI Operations Projects",
    ),
    "ai_enablement_product_management": _strategy(
        "ai_enablement_product_management",
        "Product Manager, AI Enablement | Agentic Workflows | Internal AI Tools",
        "AI enablement product manager focused on process mapping, internal AI tools, agentic workflows, prompt-based copilots, adoption, evaluation, governance, documentation, and measurable ROI across business teams.",
        (
            "AI Enablement",
            "Internal AI Products",
            "Agentic Workflows",
            "Process Mapping",
            "Workflow Automation",
            "Prompt-Based Copilots",
            "AI Tool Portfolio Management",
            "Product Requirements",
            "Scope Definition",
            "Backlog Prioritization",
            "Context Engineering",
            "Ontology Design",
            "AI Evals",
            "Human-in-the-Loop Review",
            "Release Gating",
            "Post-Launch Monitoring",
            "Adoption Tracking",
            "ROI Measurement",
            "Stakeholder Enablement",
            "Use-Case Libraries",
            "AI Governance",
        ),
        "AI Enablement Product Methods",
        (
            "Current-State Workflow Mapping",
            "Process Discovery",
            "Use-Case Intake",
            "AI Opportunity Prioritization",
            "Agentic Workflow Design",
            "Prompt Design",
            "Context Engineering",
            "Ontology Design",
            "Prototype Testing",
            "Eval Planning",
            "Human-in-the-Loop Review",
            "Release Criteria",
            "Post-Launch Monitoring",
            "Adoption Tracking",
            "ROI Reporting",
            "Documentation",
            "Workshops",
            "Office Hours",
            "Stakeholder Coaching",
        ),
        (
            "Job Fit Agent",
            "AI Product Design Operating System",
            "AI Marketing Intelligence Platform",
            "Site Audit QA Agent",
        ),
        (
            "internal AI product management",
            "process mapping and agentic workflow design",
            "evaluation, release gating, and post-launch monitoring",
            "adoption, enablement, documentation, and measurable ROI",
        ),
        (
            "OpenAI API",
            "ChatGPT",
            "Codex",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "JSON",
            "YAML",
            "Markdown",
            "Telegram Bot API",
            "Asana",
            "Figma",
            "GA4",
            "Pendo",
            "Google Tag Manager",
            "OneTrust",
            "pytest",
            "local LLMs",
            "Qwen 3",
        ),
        excluded=(),
        project_section_title="Selected AI Enablement & Agentic Workflow Projects",
    ),
   "data_platform_analytics_product": _strategy(
        "data_platform_analytics_product",
        "Manager, Performance Analytics & AI Development | BI Systems | AI-Enabled Operations",
        "Analytics and AI product leader focused on KPI frameworks, BI systems, performance dashboards, data governance, AI-enabled automation, reporting operations, and measurable business outcomes.",
        (
            "KPI Frameworks",
            "Performance Analytics",
            "Business Intelligence",
            "Executive Dashboards",
            "Self-Service Analytics",
            "Data Governance",
            "Data Quality",
            "Reporting Operations",
            "AI-Enabled Automation",
            "Predictive Insights",
            "Operational Efficiency",
            "Stakeholder Reporting",
            "Analytics Instrumentation",
            "Data Product Management",
            "Product Analytics",
            "Responsible AI",
        ),
        "Performance Analytics & AI Methods",
        (
            "KPI Design",
            "Dashboard Development",
            "Performance Reviews",
            "Anomaly Detection",
            "Benchmarking",
            "Self-Service Reporting",
            "BI Requirements",
            "Data Quality Review",
            "Reporting Governance",
            "AI Use-Case Discovery",
            "Automation Opportunity Mapping",
            "Responsible AI Practices",
            "Adoption Support",
            "Impact Measurement",
        ),
        (
                    
            "Site Audit QA Agent",
            "AI Marketing Intelligence Platform",
            "AI Product Design Operating System",
            "RWLV Priority Governor Agent",
        
        ),
        (
            "KPI frameworks and executive reporting",
            "BI systems and self-service analytics",
            "data quality and reporting governance",
            "AI-enabled automation and measurable business outcomes",
        ),
        (
            "GA4",
            "Google Tag Manager",
            "Pendo",
            "OneTrust",
            "Python",
            "SQLite",
            "OpenAI API",
            "ChatGPT",
            "GitHub / GitHub Actions",
            "Asana",
            "Figma",
            "pytest",
        ),
        project_section_title="Selected Performance Analytics & AI Development Projects",
    ),
   "ai_systems_integration": _strategy(
        "ai_systems_integration",
        "AI Systems Leader | Enterprise AI Implementation | Responsible AI Delivery",
        "AI systems leader focused on enterprise AI implementation, agentic workflows, integration planning, workflow mapping, Responsible AI practices, operational readiness, vendor coordination, production handoff, governance, and measurable business value.",
        (
            "AI Systems Strategy",
            "Enterprise AI Implementation",
            "AI Implementation",
            "Enterprise Automation",
            "Systems Integration",
            "Agentic Workflows",
            "Integration Architecture",
            "Workflow Mapping",
            "Responsible AI",
            "AI Governance",
            "Privacy Controls",
            "Production Readiness",
            "Operational Readiness",
            "Production Support Handoff",
            "Prompt Engineering",
            "RAG Evaluation",
            "Vendor Partnerships",
            "Business Value Realization",
        ),
        "AI Operating Methods",
        (
            "AI Roadmaps",
            "Workflow Mapping",
            "Integration Planning",
            "Connector Design",
            "Governance Guardrails",
            "Responsible AI Practices",
            "Privacy Review",
            "Operational Readiness",
            "Production Handoff",
            "Prompt Design",
            "RAG Evaluation",
            "Feedback Loops",
            "Agent Monitoring",
            "Vendor Coordination",
            "Usage Measurement",
            "Impact Measurement",
        ),
        (
            "RWLV Priority Governor Agent",
            "AI Product Design Operating System",
            "AI Marketing Intelligence Platform",
            "Site Audit QA Agent",
        ),
        (
            "enterprise AI implementation",
            "Responsible AI and governance",
            "operational readiness and production handoff",
            "vendor coordination and measurable business value",
        ),
        (
            "OpenAI API",
            "ChatGPT",
            "Python",
            "GitHub / GitHub Actions",
            "Figma",
            "GA4",
            "Google Tag Manager",
            "Pendo",
            "OneTrust",
            "Asana",
            "local LLMs",
            "Qwen 3",
            "SQLite",
            "Telegram Bot API",
            "pytest",
        ),
        project_section_title="Selected AI Systems & Enterprise Automation Projects",
    ),
    "website_ecommerce_digital_operations": _strategy(
        "website_ecommerce_digital_operations",
        "Senior Website Manager | E-Commerce Operations | AI-Enabled Digital Delivery",
        "Senior website and digital operations leader focused on website ownership, booking and e-commerce performance, CMS operations, vendor coordination, QA/UAT, release readiness, analytics, CRO, and AI-enabled workflow improvement.",
        (
            "Website Management",
            "E-Commerce Operations",
            "Booking Experience",
            "Digital Product Operations",
            "Website Roadmaps",
            "CMS Publishing",
            "Content Operations",
            "Landing Pages",
            "Promotions",
            "Pricing Updates",
            "Conversion Optimization",
            "Customer Journey Optimization",
            "SEO/GEO",
            "CRO",
            "Web Analytics",
            "Vendor Management",
            "Agency Management",
            "QA/UAT",
            "Release Readiness",
            "Website Launches",
            "Backlog Prioritization",
            "Acceptance Criteria",
            "AI-Enabled Digital Delivery",
        ),
        "Website, E-Commerce & AI Delivery Methods",
        (
            "Website Roadmap Planning",
            "CMS Publishing",
            "Landing Page Builds",
            "Content QA",
            "Booking Flow Review",
            "E-Commerce Merchandising",
            "Promotion Updates",
            "Pricing Updates",
            "Conversion Review",
            "Customer Journey Mapping",
            "SEO/GEO Coordination",
            "Analytics Review",
            "GA4 Measurement",
            "QA/UAT Planning",
            "Release Readiness",
            "Post-Launch Stabilization",
            "Vendor Coordination",
            "Ticket Writing",
            "Acceptance Criteria",
            "Executive Status Updates",
            "AI-Assisted QA",
            "AI-Assisted Content Workflows",
        ),
        (
            "Site Audit QA Agent",
            "AI Marketing Intelligence Platform",
            "RWLV Priority Governor Agent",
            "AI Product Design Operating System",
        ),
        (
            "website ownership and launch readiness",
            "booking and e-commerce operations",
            "CMS, content, QA/UAT, and release process",
            "analytics, CRO, vendor coordination, and AI-enabled workflows",
        ),
        (
            "WordPress",
            "CMS Platforms",
            "GA4",
            "Google Tag Manager",
            "Pendo",
            "OneTrust",
            "Asana",
            "Figma",
            "OpenAI API",
            "ChatGPT",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "pytest",
        ),
        project_section_title="Selected Website, E-Commerce & AI Delivery Projects",
    ),
    "webinar_program_technical_production": _strategy(
        "webinar_program_technical_production",
        "Webinar Program Manager | Technical Production | OpenAI-Powered Operations",
        "Webinar and digital program manager focused on technical production, event operations, stakeholder coordination, platform setup, QA, live-event troubleshooting, post-event reporting, and OpenAI-powered workflow improvement.",
        (
            "Webinar Operations",
            "Technical Production",
            "Virtual Events",
            "Livestream Production",
            "Registration Operations",
            "Run-of-Show Planning",
            "Speaker Preparation",
            "Attendee Support",
            "Incident Support",
            "Replay Publication",
            "Survey Operations",
            "Post-Event Reporting",
            "Program Management",
            "Stakeholder Coordination",
            "QA Mindset",
            "Production Deadlines",
            "Live Troubleshooting",
            "Documentation",
            "OpenAI Tooling",
            "Codex Workflows",
            "ChatGPT Workflows",
        ),
        "Webinar Production & Program Methods",
        (
            "Event Intake",
            "Webinar Scheduling",
            "Platform Configuration",
            "Registration Setup",
            "Speaker Prep",
            "Run-of-Show Documentation",
            "Rehearsal Coordination",
            "Live Production Support",
            "Attendee Support",
            "Incident Triage",
            "Recording Management",
            "Replay Publishing",
            "Survey Follow-Up",
            "Performance Reporting",
            "Post-Event Actions",
            "Stakeholder Updates",
            "QA Review",
            "Process Documentation",
            "AI-Assisted Workflow Improvement",
        ),
        (
            "Site Audit QA Agent",
            "AI Marketing Intelligence Platform",
            "RWLV Priority Governor Agent",
            "AI Product Design Operating System",
        ),
        (
            "technical production and live-event operations",
            "stakeholder coordination and deadline management",
            "QA, documentation, and repeatable program workflows",
            "OpenAI-powered operations and post-event reporting",
        ),
        (
            "ChatGPT",
            "Codex",
            "OpenAI API",
            "Asana",
            "Figma",
            "GA4",
            "Pendo",
            "Google Tag Manager",
            "OneTrust",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "pytest",
        ),
        project_section_title="Selected Webinar, QA & AI Operations Projects",
    ),
    "technical_project_program_management": _strategy(
        "technical_project_program_management", "Senior Project Manager | Digital Transformation | Cross-Functional Delivery",
        "Senior project leader focused on digital delivery, transformation programs, stakeholder alignment, requirements, release readiness, QA/UAT, vendor coordination, and executive reporting.",
        ("Program Leadership", "Digital Transformation", "Integrated Project Planning", "RAID Management", "Requirements Management", "QA & UAT", "Release Readiness", "Vendor Coordination", "Executive Reporting", "Delivery Governance"),
        "Delivery Methods", ("Integrated Project Plans", "RAID Logs", "Dependency Management", "QA Planning", "UAT Coordination", "Release Readiness", "Hypercare", "Executive Status Reporting", "Delivery Governance"),
        ("Site Audit QA Agent", "RWLV Priority Governor Agent", "AI Marketing Intelligence Platform", "AI Product Design Operating System"),
        ("roadmap and dependency management", "QA/UAT and release readiness", "vendor coordination", "executive status and delivery governance"),
        ("Asana", "GitHub / GitHub Actions", "Figma", "GA4", "Google Tag Manager", "Pendo", "OneTrust", "Python"),
        project_section_title="Selected Delivery, Product & AI Systems"),
    "applied_ai_strategy_consulting": _strategy(
        "applied_ai_strategy_consulting",
        "Enterprise AI Architect | Agentic AI Solutions | Governance & Operational Readiness",
        "Enterprise AI architect focused on agentic AI solution design, enterprise architecture, integration planning, AI use-case discovery, technical roadmaps, governance documentation, operational readiness, stakeholder advisory, and measurable business outcomes.",
        (
            "Agentic AI Solution Design",
            "Applied AI Strategy",
            "Generative AI Workflows",
            "RAG",
            "Multi-Agent Systems",
            "AI Use-Case Discovery",
            "Value Qualification",
            "Workflow Automation",
            "Process Re-engineering",
            "AI Operating Models",
            "Governance Documentation",
            "Responsible AI",
            "Production Handoff",
            "Stakeholder Advisory",
            "Business Case Development",
            "Measurable Value",
            "Enterprise Architecture",
            "Integration Architecture",
            "API Layers",
            "Security Layers",
            "Roadmap Planning",
            "Pilot-to-Production Delivery",
            "Operational Readiness",
        ),
        "Applied AI Delivery Methods",
        (
            "AI Use-Case Discovery",
            "Value Qualification",
            "Workflow Mapping",
            "Process Re-engineering",
            "Agentic Workflow Design",
            "Prompt Design",
            "RAG Evaluation",
            "Prototype Testing",
            "Production Readiness",
            "Governance Artifacts",
            "Responsible AI Practices",
            "Operating Model Recommendations",
            "Stakeholder Workshops",
            "Executive Updates",
            "Impact Measurement",
        ),
        (
            "AI Product Design Operating System",
            "AI Marketing Intelligence Platform",
            "Site Audit QA Agent",
            "RWLV Priority Governor Agent",
        ),
        (
            "applied AI strategy and solution design",
            "workflow automation and process change",
            "governance documentation and responsible AI",
            "stakeholder advisory and measurable business value",
        ),
        (
            "OpenAI API",
            "GPT-5.5",
            "OpenClaw",
            "Hermes Agent",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "JSON",
            "YAML",
            "Markdown",
            "Asana",
            "Figma",
            "GA4",
            "Pendo",
            "Google Tag Manager",
            "OneTrust",
            "pytest",
        ),
        excluded=("Job Fit Agent",),
        project_section_title="Selected Applied AI Strategy & Agentic Workflow Projects",
    ),
    "ai_workflow_automation_solutions": _strategy(
        "ai_workflow_automation_solutions",
        "Senior Product Manager | Agentic Workflows | AI-Powered Automation",
        "Senior product manager focused on agentic workflows, AI-powered automation, hands-on prototyping, workflow discovery, production handoff, adoption, governance documentation, and measurable business outcomes.",
        (
            "Agentic Workflows",
            "AI-Powered Automation",
            "Workflow Discovery",
            "AI Prototyping",
            "Product Requirements",
            "Backlog Prioritization",
            "Stakeholder Discovery",
            "Business Process Improvement",
            "Production Handoff",
            "Adoption Measurement",
            "Operational Efficiency",
            "Governance Documentation",
            "RAG",
            "Prompt Engineering",
            "LLM Workflows",
        ),
        "Agentic Workflow Methods",
        (
            "Workflow Mapping",
            "User Observation",
            "Use Case Intake",
            "Rapid Prototyping",
            "Prompt Design",
            "RAG Evaluation",
            "Prototype Testing",
            "User Feedback Loops",
            "Production Readiness",
            "Governance Artifacts",
            "Adoption Tracking",
            "Impact Measurement",
            "Executive Updates",
        ),
        (
            "AI Product Design Operating System",
            "Site Audit QA Agent",
            "AI Marketing Intelligence Platform",
            "RWLV Priority Governor Agent",
            "Job Fit Agent",
        ),
        (
            "workflow discovery and product requirements",
            "hands-on AI prototyping",
            "prototype-to-production handoff",
            "adoption and measurable business outcomes",
        ),
        (
            "OpenAI API",
            "GPT-5.5",
            "OpenClaw",
            "Hermes Agent",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "JSON",
            "YAML",
            "Markdown",
            "Telegram Bot API",
            "Asana",
            "Figma",
            "GA4",
            "Pendo",
            "pytest",
        ),
        excluded=(),
        project_section_title="Selected Agentic Workflow & AI Automation Projects",
    ),
    "product_marketing": _strategy(
        "product_marketing", "Product Marketing Manager | AI-Enabled Product Storytelling | GTM Strategy",
        "Product marketing leader focused on product narrative, launch strategy, technical fluency, AI-enabled research, enablement content, positioning, and adoption.",
        ("Product Marketing", "Positioning", "GTM Strategy", "Launch Messaging", "Sales Enablement", "Product Narrative", "AI-Enabled Research", "Adoption"),
        "Go-to-Market Methods", ("Positioning", "Messaging", "Launch Planning", "Audience Research", "Sales Enablement", "Adoption Measurement"),
        ("AI Marketing Intelligence Platform", "AI Product Design Operating System", "Site Audit QA Agent", "RWLV Priority Governor Agent"),
        ("launch execution", "positioning and narrative", "cross-functional enablement", "adoption outcomes")),
    "local_contract_consulting": _strategy(
        "local_contract_consulting", "AI Workflow Consultant | Hospitality Automation | Practical AI Implementation",
        "AI workflow consultant focused on practical AI implementation, workflow diagnostics, stakeholder discovery, automation pilots, hospitality operations, and measurable operational improvement.",
        ("AI Consulting", "Workflow Diagnostics", "Hospitality Automation", "Stakeholder Discovery", "Automation Pilots", "Process Improvement", "Practical AI Implementation"),
        "Consulting Methods", ("Discovery Workshops", "Workflow Diagnostics", "Pilot Scoping", "Implementation Planning", "Stakeholder Training", "Impact Measurement"),
        ("AI Marketing Intelligence Platform", "Site Audit QA Agent", "RWLV Priority Governor Agent", "AI Product Design Operating System"),
        ("client discovery", "practical implementation", "hospitality operations", "measurable process improvement")),
    "ecommerce_product_management": _strategy(
        "ecommerce_product_management",
        "Senior Digital Product Manager | Enterprise Commerce | AI-Enabled Product Delivery",
        "Senior digital product manager focused on enterprise ecommerce, shopping journeys, product roadmaps, discovery, user stories, acceptance criteria, analytics-informed prioritization, checkout and booking flows, release readiness, and AI-enabled product delivery.",
        (
            "E-Commerce Product Management",
            "Digital Product Strategy",
            "Product Ownership",
            "Backlog Management",
            "User Stories",
            "Scope Definition",
            "Acceptance Criteria",
            "Checkout Flows",
            "Booking Flows",
            "Customer Journey Optimization",
            "Conversion Optimization",
            "Agile/Scrum",
            "Engineering Collaboration",
            "RESTful APIs",
            "Web Technologies",
            "Performance Metrics",
            "Backend Integrations",
            "QA/UAT",
            "AI-Enabled Product Delivery",
        ),
        "E-Commerce Product Methods",
        (
            "Product Discovery",
            "Backlog Prioritization",
            "User Story Writing",
            "Acceptance Criteria",
            "Checkout Flow Review",
            "Booking Flow Review",
            "Customer Journey Mapping",
            "Conversion Review",
            "Analytics Review",
            "Engineering Handoff",
            "Agile/Scrum Delivery",
            "QA/UAT Planning",
            "Release Readiness",
            "Stakeholder Updates",
            "AI-Assisted Product Workflows",
        ),
        (
            "Site Audit QA Agent",
            "AI Product Design Operating System",
            "AI Marketing Intelligence Platform",
            "RWLV Priority Governor Agent",
        ),
        (
            "e-commerce and booking flow optimization",
            "backlog management and user stories",
            "engineering collaboration and release readiness",
            "AI-enabled product delivery and customer journey improvement",
        ),
        (
            "Asana",
            "Figma",
            "GA4",
            "Google Tag Manager",
            "Pendo",
            "OneTrust",
            "OpenAI API",
            "ChatGPT",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "pytest",
        ),
        project_section_title="Selected E-Commerce Product & AI Delivery Projects",
    ),
    "product_management": _strategy(
        "product_management", "Technical Product Manager | AI-Powered Digital Products | Product Analytics",
        "Technical product builder focused on AI-enabled workflow systems, internal tools, product analytics, and agentic operations.",
        ("Technical Product Management", "Product Roadmaps", "Product Discovery", "Feature Prioritization", "Product Analytics", "Requirements", "Stakeholder Alignment", "AI-Assisted Product Development"),
        "Product Methodologies", ("Product Roadmap", "Product Discovery", "Feature Prioritization", "User Behavior Analysis", "Product Requirements", "User Stories", "Backlog Prioritization", "Product Lifecycle", "Stakeholder Alignment"),
        ("AI Product Design Operating System", "RWLV Priority Governor Agent", "Job Fit Agent", "AI Marketing Intelligence Platform"),
        ("product discovery and requirements", "roadmap prioritization", "analytics-informed decisions", "cross-functional execution"),
        ("OpenClaw", "Hermes Agent", "GPT-5.5", "OpenAI API", "local LLMs", "Qwen 3", "Python", "GitHub / GitHub Actions", "SQLite", "Telegram Bot API", "Asana", "Pendo", "GA4", "Google Tag Manager", "OneTrust", "Figma", "pytest"),
        excluded=()),
    "content_portfolio_product_management": _strategy(
        "content_portfolio_product_management",
        "Content Product Manager | Portfolio Roadmaps | GTM & Commercial Enablement",
        "Content product manager focused on portfolio roadmap management, product planning, go-to-market execution, commercial enablement, stakeholder alignment, performance analytics, and post-launch optimization.",
        (
            "Content Product Management",
            "Portfolio Management",
            "Product Roadmaps",
            "Roadmap Prioritization",
            "Product Lifecycle",
            "Go-To-Market Planning",
            "Commercial Enablement",
            "Sales Enablement",
            "Stakeholder Alignment",
            "Performance Analytics",
            "Market Insights",
            "Customer Insights",
            "Launch Planning",
            "Post-Launch Optimization",
            "Cross-Functional Delivery",
            "Product Positioning",
            "Messaging",
            "KPI Monitoring",
            "Continuous Improvement",
        ),
        "Content Product & GTM Methods",
        (
            "Portfolio Roadmap Planning",
            "Release Prioritization",
            "Product Lifecycle Management",
            "GTM Planning",
            "Sales Enablement",
            "Commercial Readiness",
            "Positioning",
            "Messaging",
            "Stakeholder Communication",
            "Performance Review",
            "KPI Monitoring",
            "Market Analysis",
            "Customer Insight Review",
            "Post-Launch Optimization",
            "Roadmap Updates",
            "Cross-Functional Alignment",
        ),
        (
            "AI Marketing Intelligence Platform",
            "AI Product Design Operating System",
            "RWLV Priority Governor Agent",
            "Site Audit QA Agent",
        ),
        (
            "portfolio roadmap management",
            "GTM planning and commercial enablement",
            "performance analytics and market insights",
            "cross-functional product execution",
        ),
        (
            "Asana",
            "Figma",
            "GA4",
            "Pendo",
            "Google Tag Manager",
            "OneTrust",
            "OpenAI API",
            "ChatGPT",
            "Python",
            "GitHub / GitHub Actions",
            "SQLite",
            "pytest",
        ),
        project_section_title="Selected Content Product, GTM & Analytics Projects",
    ),
}


KEYWORDS = {
    "ai_strategy_transformation": ("ai strategy", "ai transformation", "enterprise ai", "ai literacy", "ai academy", "ai adoption", "change enablement", "communities of practice", "champion network", "responsible ai", "workflow-integrated automation", "productivity outcomes", "senior leader updates", "stakeholder communications", "scalable ai programs"),
    "ai_data_operations_project_lead": (
        "strategic project lead",
        "ai data",
        "frontier ai labs",
        "voice model",
        "voice data",
        "reinforcement learning",
        "environment data",
        "data projects",
        "data delivery",
        "own delivery",
        "end-to-end delivery",
        "lab requirements",
        "customer requirements",
        "source data",
        "global contributor network",
        "contributor network",
        "quality control",
        "qc systems",
        "scalable qc",
        "customer relationships",
        "coordinate across all sides",
        "high agency",
        "generalist",
        "unstructured",
        "early-stage",
        "fast-moving",
        "operationally heavy",
        "long hours",
        "human-data startup",
        "product management",
        "founder",
        "operations",
        "delivery",
    ), 
    "ai_solutions_architecture": (
    "manager ai center of excellence solutions architect",
    "ai center of excellence",
    "solutions architect",
    "ai architecture",
    "ai solutions development",
    "ai experiments",
    "knowledge assistants",
    "ai agents",
    "agentic workflows",
    "technical specifications",
    "technical specs",
    "evaluate ai systems",
    "evals",
    "benchmarks",
    "automated tests",
    "model evaluations",
    "ai marketplace",
    "alliance ecosystem",
    "stakeholders",
    "developers",
    "data scientists",
    "audit tax advisory",
    "functional stakeholders",
    "ai technical guidance",
    "components",
    "solutions",
    "continuous learning",
    "skilling",
    ),
    "agentic_operations_architecture": (
        "agentic operations architect",
        "agentic operations",
        "service transformation",
        "cxt",
        "agentic service workflows",
        "reusable capabilities",
        "patterns",
        "primitives",
        "standards",
        "tooling",
        "workflow patterns",
        "orchestration",
        "human-in-the-loop",
        "hitl",
        "override",
        "escalation logic",
        "quality safeguards",
        "prototype workflows",
        "platform gaps",
        "automation opportunities",
        "volume risk customer impact",
        "sops",
        "operational metrics",
        "interaction data",
        "workflow performance",
        "solve rate",
        "assist rate",
        "containment",
        "escalation quality",
        "regression",
        "legal",
        "security",
        "compliance",
        "responsible ai",
        "governance",
        "risk management",
        "rag",
        "retrieval quality",
        "data quality",
        "data governance",
        "mcp",
        "multi-agent",
    ),
    "ai_enablement_product_management": (
        "product manager, ai enablement",
        "ai enablement",
        "centralized ai operations",
        "ai operations",
        "internal ai tools",
        "internal users",
        "agentic workflows",
        "prompt-based copilots",
        "process mapping",
        "map processes",
        "current-state workflows",
        "workflow mapping",
        "portfolio of internal ai tools",
        "prototype to production",
        "human-in-the-loop",
        "post-launch monitoring",
        "rollout criteria",
        "evaluation",
        "evals",
        "eval-driven development",
        "release gating",
        "context engineering",
        "ontology design",
        "roi",
        "adoption",
        "track adoption",
        "usage metrics",
        "make the roi case",
        "workshops",
        "office hours",
        "coaching",
        "enablement content",
        "use-case libraries",
        "ai governance",
        "acceptable-use policies",
        "data-handling guardrails",
        "frontier ai",
        "codex",
        "claude code",
        "anti-gravity",
        "supergrok",
        "rag",
        "hallucination mitigation",
        "multi-agent orchestration",
    ),
    "webinar_program_technical_production": (
        "webinar program manager",
        "technical production",
        "webinar",
        "webinars",
        "livestream",
        "livestreams",
        "virtual events",
        "virtual conferences",
        "restream",
        "gradual",
        "registration management",
        "registration operations",
        "speaker preparation",
        "speaker prep",
        "attendee support",
        "incident support",
        "recordings",
        "replays",
        "replay publication",
        "surveys",
        "post-event reporting",
        "run-of-show",
        "technical production",
        "live events",
        "real-time troubleshooting",
        "production deadlines",
        "openai products",
        "chatgpt",
        "codex",
        "public-sector audiences",
        "government audiences",
        "program operations",
    ),
    "data_platform_analytics_product": (
        "performance analytics",
        "performance measurement",
        "kpi",
        "kpi frameworks",
        "business intelligence",
        "bi infrastructure",
        "executive dashboards",
        "dashboards",
        "self-service analytics",
        "reporting platforms",
        "data warehouses",
        "etl",
        "data modeling",
        "data governance",
        "data quality",
        "reporting governance",
        "anomalies",
        "benchmarking",
        "predictive models",
        "forecasting accuracy",
        "intelligent automation",
        "ai development",
        "ai-powered solutions",
        "machine learning",
        "responsible ai development",
        "bias mitigation",
        "transparency",
        "operational efficiency",
        "business insights",
        "data-driven decision-making",
        "sql",
        "power bi",
        "tableau",
        "qlik",

        # CDP / data platform keywords for Caesars-style roles
        "data platform",
        "cdp",
        "single customer view",
        "customer data",
        "identity resolution",
        "profile stitching",
        "event tracking",
        "telemetry",
        "taxonomy",
        "schema",
        "schemas",
        "observability",
        "segmentation",
        "activation",
        "snowflake",
        "bigquery",
        "kafka",
        "pii",
        "consent",
    ),
    "ai_systems_integration": (
        "ai systems",
        "ai stack",
        "ai implementation",
        "enterprise ai",
        "ai applications",
        "generative ai solutions",
        "integration",
        "architecture",
        "technical standards",
        "connectors",
        "governance guardrails",
        "responsible ai",
        "ai governance",
        "privacy controls",
        "model governance",
        "human-in-the-loop",
        "operational readiness",
        "production readiness",
        "production support",
        "production handoff",
        "llm orchestration",
        "agent orchestration",
        "rag architectures",
        "rag",
        "vector databases",
        "prompt engineering",
        "microservices",
        "backend pipelines",
        "azure openai",
        "microsoft ai",
        "healthcare compliance",
        "business value realization",
        "deployed agents",
        "automations",
        "feedback loops",
        "vendor partners",
        "token usage",
        "ai roadmap",
        "department workflows",
        "data intelligence",
    ),
    "website_ecommerce_digital_operations": (
        "website manager",
        "senior website manager",
        "website management",
        "website roadmap",
        "website launch",
        "website launches",
        "new website",
        "booking platform",
        "booking experience",
        "booking flows",
        "e-commerce",
        "ecommerce",
        "e-commerce operation",
        "e-commerce performance",
        "checkout flows",
        "payment experience",
        "promotions",
        "pricing",
        "merchandising",
        "cms",
        "cms publishing",
        "content updates",
        "landing pages",
        "content operations",
        "seo",
        "geo",
        "cro",
        "conversion",
        "customer journey",
        "web analytics",
        "uat",
        "qa",
        "release readiness",
        "post-launch stabilization",
        "vendor management",
        "agency",
        "developers",
        "acceptance criteria",
        "website product backlog",
        "release process",
        "production fixes",
        "apis",
        "web integrations",
        "data flows",
        "ai tools",
        "quality assurance",
        "internal workflows",
    ),
    "technical_consulting_solutions_implementation": (
        "technical consultant",
        "solutions engineering",
        "solutions consultant",
        "implementation",
        "implementation support",
        "customer-facing technical",
        "customer activation",
        "account management",
        "technical advisor",
        "technical discovery",
        "customer requirements",
        "scalable solutions",
        "erp",
        "hris",
        "api integrations",
        "api",
        "integration logic",
        "system architecture",
        "configuration",
        "configuration decisions",
        "technical hurdles",
        "technical workstreams",
        "onboarding",
        "time-to-value",
        "customer success",
        "post-sales",
        "product roadmap",
        "product feedback",
        "documentation",
        "internal tooling",
        "finance workflows",
        "accounting workflows",
        "commercial",
        "mid-market",
        "netSuite",
        "sage intacct",
        "microsoft dynamics",
        "oracle fusion",
        "sap",
    ),
    "technical_project_program_management": ("project manager", "program manager", "transformation", "ecommerce transformation", "roadmap execution", "integrated project plan", "raid", "uat", "qa", "hypercare", "vendor coordination", "executive status", "delivery governance", "dependencies", "release readiness"),
    "applied_ai_strategy_consulting": (
        "applied ai strategist",
        "applied ai",
        "ai strategist",
        "trusted advisor",
        "solution architecture",
        "agentic ai solution architecture",
        "production-grade ai agents",
        "production ai solutions",
        "generative ai application development",
        "rag",
        "multi-agent systems",
        "langchain",
        "langgraph",
        "llmops",
        "mlops",
        "ai platform design",
        "ai governance",
        "responsible ai",
        "rbac",
        "abac",
        "ai use-case discovery",
        "value qualification",
        "business case development",
        "process re-engineering",
        "workflow automation",
        "ai operating model",
        "organization design",
        "client relationship",
        "client stakeholders",
        "measurable value",
        "production deployment",
        "adoption",
        "consulting environment",
        "private equity",
        "portfolio companies",
        "enterprise ai architect",
        "enterprise ai architecture",
        "enterprise architecture",
        "ai architecture",
        "target technical architecture",
        "technical roadmaps",
        "roadmap planning",
        "phased implementation",
        "pilot to production",
        "production-ready architectures",
        "data platforms",
        "iam",
        "security layers",
        "integration layers",
        "fallback design",
        "grounding",
        "orchestration",
        "stakeholder workshop",
        "stakeholder facilitation",
        "architecture communication",
        "multi-cloud",
        "operational readiness",
        "governance controls",
        "risk controls",
        "compliance controls",
    ),
    "ai_workflow_automation_solutions": (
        "workflow automation",
        "ai workflow",
        "ai workflows",
        "agentic workflow",
        "agentic workflows",
        "ai-powered workflow",
        "ai-powered workflows",
        "ai-enabled automation",
        "intelligent automation",
        "llm",
        "large language models",
        "prompt engineering",
        "rag",
        "retrieval-augmented generation",
        "rapidly prototype",
        "prototype",
        "prototyping",
        "production deployment",
        "adoption",
        "operational efficiency",
        "quality improvements",
        "business impact",
        "audit artifacts",
        "governance",
        "workflow documentation",
        "reusable solutions",
        "development practices",
        "internal tools",
        "process automation",
        "api workflows",
        "implementation",
    ),
    "product_marketing": ("product marketing", "positioning", "launch messaging", "enablement", "changelog", "go-to-market", "gtm strategy", "narrative", "sales enablement"),
    "local_contract_consulting": ("consultant", "contract", "1099", "workflow diagnostic", "local business", "hospitality operator", "automation project", "implementation partner", "process improvement"),
    "ecommerce_product_management": (
        "ecommerce product manager",
        "e-commerce product manager",
        "junior ecommerce product manager",
        "junior e-commerce product manager",
        "product ownership",
        "digital product strategy",
        "backlog",
        "backlogs",
        "user stories",
        "clear user stories",
        "scope",
        "acceptance criteria",
        "e-commerce",
        "ecommerce",
        "digital transaction",
        "digital transaction environments",
        "checkout",
        "checkout flows",
        "booking flows",
        "conversion rates",
        "user journeys",
        "customer journey",
        "shopify",
        "magento",
        "salesforce commerce cloud",
        "html",
        "css",
        "react",
        "restful apis",
        "backend integrations",
        "performance metrics",
        "agile",
        "scrum",
        "ci/cd",
        "continuous integration",
        "continuous delivery",
        "cursor",
        "windsurf",
        "claude code",
        "gemini cli",
        "codex",
        "copilot cli",
        "ai-enthusiastic",
    ),
    "product_management": ("product manager", "product management", "product lead", "product roadmap", "product discovery", "feature prioritization", "backlog"),
        "content_portfolio_product_management": (
        "content product manager",
        "games portfolio",
        "game portfolio",
        "portfolio management",
        "studio roadmap",
        "studio roadmaps",
        "content strategy",
        "game releases",
        "release prioritization",
        "commercial impact",
        "player value",
        "product lifecycle",
        "post-release optimisation",
        "post-release optimization",
        "game development lifecycle",
        "studio teams",
        "creative studios",
        "game studios",
        "go-to-market",
        "gtm planning",
        "sales enablement",
        "commercial enablement",
        "commercial teams",
        "global content strategy",
        "regional market",
        "market dynamics",
        "market insights",
        "player behaviour",
        "player behavior",
        "portfolio performance",
        "commercial outcomes",
        "roadmap",
        "kpis",
        "testing",
        "analysis",
        "iteration",
        "entertainment",
        "media industry",
        "igaming",
        "gaming",
    ),
}


def classify_resume_strategy(job_title: str, description: str = "", role_family: str = "") -> ResumeStrategy:
    """Score exact phrases deterministically; title matches receive a 3x tie-break weight."""
    title = job_title.casefold()
    body = f"{description} {role_family}".casefold()
    scores = {lane: sum(3 for term in terms if term in title) + sum(1 for term in terms if term in body)
              for lane, terms in KEYWORDS.items()}
    ranked = sorted(scores.items(), key=lambda item: (-item[1], list(KEYWORDS).index(item[0])))
    lane, score = ranked[0]
    runner_up = ranked[1][1]
    low_confidence = score < 2
    if low_confidence:
        lane = "product_management"
    base = STRATEGIES[lane]
    return ResumeStrategy(**{**base.__dict__, "score": score, "runner_up_score": runner_up, "low_confidence": low_confidence})
