greenhouse:
  - stripe
  - duolingo
  - amplitude
  - figma
  - cloudflare
  - vercel

ashby:
  - notion
  - cursor
  - perplexity
  - elevenlabs
  - replit
  - linear
  - langchain
  - modal
  - mercor
